### ISSUE TITLE
UserLink.label is deprecated

### ISSUE THREAD

**Issue by 2naive** [pocka/slack-message-parser#31]
Hi,

https://github.com/pocka/slack-message-parser/blob/master/src/types/Node.ts#L50
-- label field is deprecated due to all user mentions are in <@W123> format now:
https://api.slack.com/changelog/2017-09-the-one-about-usernames#how-do-i-prepare
moreover, they plan to do the same for channels:
https://api.slack.com/changelog/2017-09-the-one-about-usernames#how-do-i-prepare__just-one-more-thing-channels

and a question: why you use Node[] -- an array of labels for all nodes having label? what's the use case?

Thanks!

**Comment by pocka** [comment]
Although they announced that a long time ago (not so long?), [their parsing guide](https://api.slack.com/reference/surfaces/formatting#retrieving-messages) still recommends parsing pipe character (`|`) for labeling purpose. Also, I think it's better to keep the feature until Slack officially drops it and introduces an incompatible syntax that collides with the label syntax. It's not just for the robustness principle, but also for "backward compatibility", e.g. parsing old logs.

> why you use Node[] -- an array of labels for all nodes having label? what's the use case?

Because they are formatted texts, at least in normal links.
Sadly there are no public official specs for their text formatting available, so we need to guess the syntax.

Maybe you can't create a message such as `<@U0123|*bold* and _italic_>` via Slack apps. However, both the user link and the channel link seem to belong to something like "link syntax", and you can use text formatting in normal links (e.g. `<http://example.com|*bold* and _italic_>`). This and [the link parser accounting for all sort of link types](https://github.com/pocka/slack-message-parser/blob/c243f9217541876b00a02d24a9dfda82d8f65e2c/src/parser.ts#L150-L203), is the reason for the `label?: Node[]`.

---

If you find a bug related to those parsing methods, please open a new issue. An expected message (node tree or screenshot) and an actual one would help a lot.
